### ISSUE TITLE
Add ability to provision multiple environments.

### ISSUE THREAD

**Issue by jlebon** [jlebon/redhat-ci#12]
This will be relevant for e.g. clustered tests, but also in cases when one wants a toy VM they can control remotely, as is the case with the rpm-ostree vmcheck suite.

**Comment by jlebon** [comment]
Tentative spec addition:

``` yaml
# REQUIRED (one of 'host' or 'container' or 'cluster')
# Provision multiple hosts.
cluster:
    # REQUIRED
    # List of hosts to provision. The same keys as above are
    # accepted.
    hosts:
      # REQUIRED
      # The 'name' key is used to inject an environment
      # variable named RHCI_<name>_IP whose value is the IP
      # address of the provisioned host.
      - name: host1
        distro: centos/7/atomic
        ostree: latest
      - name: host2
        distro: fedora/24/cloud
    # OPTIONAL
    # If specified, the scripts are run on this container.
    # If omitted, the scripts are run on the first host
    # listed in the 'hosts' list.
    container:
        image: fedora:24
```
