### ISSUE TITLE
Provide support for an overall status

### ISSUE THREAD

**Issue by jlebon** [jlebon/redhat-ci#18]
Some services like Homu watch for statuses to determine whether to merge a commit. In those cases, it might be easier for it to watch for a single "overall" status rather than multiple statuses, whose set may change over time.

**Comment by jlebon** [comment]
Tentative spec:

```yaml
# OPTIONAL
# Specify the context group to which this testsuite belongs.
# This commit status context will be marked as successful
# only if all the member testsuites are successful. If
# omitted, no group context is defined.
context-group: 'Red Hat CI - Overall status'
```

For example, in the Homu use case, this would allow you to define the set of testsuites on which we want to gate (e.g. you might have a testsuite that is flaky/a work in progress).

**Comment by cgwalters** [comment]
Seems OK.  Though I wonder if it's simpler to support rolling suites under a single context by default, like:

`context: optional/test1` and `context: optional/test2` would result in a single `optional` context that merged the two suites.  Call them "context name" and "suite name".  The suite name would then be a prefix in that case for uploaded artifacts etc.

The advantage would be less visual noise per PR.

Something like this:

```
branches:
    - master
    - auto
    - try

context: baseline/sanitize-undefined

container:
    image: projectatomic/ostree-tester

env:
    CFLAGS: '-fsanitize=undefined'

build:
    config-opts: >
      --prefix=/usr
      --libdir=/usr/lib64
      --enable-installed-tests
      --enable-gtk-doc

tests:
    - make syntax-check
    - make check
    - gnome-desktop-testing-runner ostree
    - sudo --user=testuser gnome-desktop-testing-runner ostree

timeout: 30m

artifacts:
    - test-suite.log

---

context: baseline/clang
inherit: true
env:
    CC: 'clang'
    CFLAGS: '-Werror=unused-variable'
tests:
artifacts:

---

inherit: true
context: optional/ASAN
# Until the container is regenerated
packages:
  - libasan

env:
    # Suppress leak detection in configure (and build, since
    # g-ir-scanner uses glib), because sadly some of them leak
    ASAN_OPTIONS: 'detect_leaks=false'
    CFLAGS: '-fsanitize=address -fno-omit-frame-pointer'

tests:
    - env OT_SKIP_READDIR_RAND=1 ASAN_OPTIONS='detect_leaks=true:malloc_context_size=20' make check

artifacts:
    - config.log
    - test-suite.log
```
