### ISSUE TITLE
Allow some field values to refer to other field values by name

### ISSUE THREAD

**Issue by jlebon** [jlebon/redhat-ci#42]
For example, it's common for the `context` to be the same as the `distro` used. In that case, it would be nice if one could just do something like:

```yaml
context: $distro
```

Which gets properly inherited and such.

Another potential use:

```yaml
env:
  TEST: mytest

context: "$distro | $TEST"
```

Of course, this would require careful examination of string origins and sanitization to make sure there's no nastiness possible.
